### ISSUE TITLE
An error occurred when the model was running

### ISSUE THREAD

**Issue by 35KevinDurant** [matlab-deep-learning/Pretrained-Yolov9-Network-For-Object-Detection#2]
Hello
I get this error when the model is running, and I want to know how you solved it.
Thank you
![1](https://github.com/user-attachments/assets/bdca90f3-751e-48c5-abc4-450bde92856a)
![2](https://github.com/user-attachments/assets/ae14a305-d68f-4404-9725-3dc4800b97fd)

**Comment by zuberkhan175** [comment]
Hi, 
This issue is likely due to missing "Deep Learning Toolbox Converter for ONNX Model Format" add-on in your MATLAB which is one of the requirements as mentioned here: [Requirements](https://github.com/matlab-deep-learning/Pretrained-YOLOv8-Network-For-Object-Detection?tab=readme-ov-file#requirements:~:text=Ultralytics%20Licensing.-,Requirements,-MATLAB%C2%AE%20R2024a%20or)
I would recommend you to install it using the Add-On Explorer.
